name: Deploy thorctl
description: Build and deploy a thorctl version
inputs:
  environment:
    description: "Environment to target (staging or production)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Build thorctl docker image
      run: |
        docker build -t thorctl:$GITHUB_SHA .

    - name: Tag build image
      run: |
        docker tag thorctl:$GITHUB_SHA gcr.io/moeyens-thor-dev/thorctl:$GITHUB_SHA

    - name: Set up cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Log in to docker
      run: |
        gcloud auth configure-docker

    - name: Push image to repository
      run: |
        docker push gcr.io/moeyens-thor-dev/thorctl:$GITHUB_SHA

    - name: Push image to ${{ inputs.environment }}
      run: |
        docker push gcr.io/moeyens-thor-dev/thorctl:${{ inputs.environment }}-tasks-latest
    - name: Update production autoscaler
      run: |
        infra/autoscaler/update.sh ${{ inputs.environment }}
