name: build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build thorctl docker image
      run: |
        docker build -t thorctl:${{ github.sha }} .

    - name: Set up cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Log in to docker
      run: |
        gcloud auth configure-docker

    - name: Tag and push built image
      run: |
        docker tag thorctl:${{ github.sha }} gcr.io/moeyens-thor-dev/thorctl:${{ github.sha }}
        docker push gcr.io/moeyens-thor-dev/thorctl:${{ github.sha }}
