name: deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build thorctl docker image
      run: |
        docker build -t thorctl:$GITHUB_SHA .

    - name: Tag built image
      run: |
        docker tag thorctl:$GITHUB_SHA gcr.io/moeyens-thor-dev/thorctl:$GITHUB_SHA
        docker tag thorctl:$GITHUB_SHA gcr.io/moeyens-thor-dev/thorctl:production-tasks-latest

    - name: Set up cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Log in to docker
      run: |
        gcloud auth configure-docker

    - name: Push image
      run: |
        docker push gcr.io/moeyens-thor-dev/thorctl:production-tasks-latest
        docker push gcr.io/moeyens-thor-dev/thorctl:$GITHUB_SHA

    - name: Update autoscaler
      run: |
        cd infra/autoscaler
        # Commented out for now
        # ./update.sh
