name: build

on:
  push:
    branches:
      - main
      - production
      - staging

jobs:
  build-worker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build THOR worker
      run: |
        docker build -t thor-worker -f Dockerfile.worker .
    - name: Tag THOR worker

      run: |
        cd
        pip install pip --upgrade
        pip install -r requirements.txt -r dev-requirements.txt
        cd thor
        pip install --use-feature=in-tree-build .
        cd ../

    - name: Install package
      run: |
        pip install .

    - name: Verify installation works
      run: |
        thorctl --help

  build-autoscaler:
    runs-on: ubuntu-latest

  build-client-lib:
    runs-on: ubuntu-latest
