name: production-deploy
on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build or pull thorctl docker image
      run: |
        docker pull gcr.io/moeyens-thor-dev/thorctl:${{ github.sha }} || true
        if docker images gcr.io/moeyens-thor-dev/thorctl:${{ github.sha }} | grep -q "${{ github.sha }}"; then
            echo "Docker pull succeeded"
        else
            echo "Building docker image"
            docker build -t gcr.io/moeyens-thor-dev/thorctl:${{ github.sha }}
        fi
    - name: Set up cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Log in to docker
      run: |
        gcloud auth configure-docker

    - name: Push image to production
      run: |
        docker tag gcr.io/moeyens-thor/dev/thorctl:$GITHUB_SHA gcr.io/moeyens-thor-dev/thorctl:production-tasks-latest
        docker push gcr.io/moeyens-thor-dev/thorctl:production-tasks-latest
    - name: Update production autoscaler
      run: |
        infra/autoscaler/update.sh production
