name: staging-deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: .github/actions/deploy
      name: Deploy to staging
      with:
        environment: staging
        token: ${{ github.token }}
        gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        gcp_service_account_key: ${{ secrets.GCP_SA_KEY }}
