name: verify_dependencies

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: thor
        python-version: 3.8
        channels: conda-forge
        mamba-version: "*"

    - name: Install dependencies
      run: |
        conda install openorb
        pip install pip --upgrade
        pip install -r requirements.txt -r dev-requirements.txt
        cd thor
        pip install --use-feature=in-tree-build .
        cd ../

    - name: Install package
      run: |
        pip install .

    - name: Verify installation works
      run: |
        thorctl --help
