name: verify_dependencies

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: thor
        python-version: 3.8
        channels: conda-forge
        mamba-version: "*"

    - name: Install dependencies
      run: |
        conda install openorb
        pip install -r requirements.txt -r dev-requirements.txt

    - name: Install package
      run: |
        pip install .

    - name: Verify installation works
      run: |
        thorctl --help

    - name: Run unit tests
      run: pytest .

  integration-test:
    concurrency: integration-test
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq
        env:
          RABBITMQ_DEFAULT_USER: thor
          RABBITMQ_DEFAULT_PASS: security_is_very_important
        ports:
          - 5672:5672

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: thor
        python-version: 3.8
        channels: conda-forge
        mamba-version: "*"

    - name: Install dependencies
      run: |
        conda install openorb
        pip install -r requirements.txt -r dev-requirements.txt

    - name: Install package
      run: |
        pip install .

    - name: Run integration tests
      env:
        RABBIT_USER: thor
        RABBIT_PASSWORD: security_is_very_important
        THORCTL_INTEGRATION_TEST: yes
      run: pytest .
