name: verify_dependencies

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: thor
        python-version: 3.8
        channels: conda-forge
        mamba-version: "*"

    - name: Install dependencies
      run: |
        conda install openorb
        pip install -r requirements.txt -r dev-requirements.txt

    - name: Install package
      run: |
        pip install .

    - name: Verify installation works
      run: |
        thorctl --help
